### ISSUE TITLE
bootstrapImputation function not compatible with Seurat v3

### ISSUE THREAD

**Issue by gloriabk** [seasamgo/rescue#1]
Hi,
I just noticed that _bootstrapImputation_ function is incompatible with Seurat v3 since it is using FindVariableGenes instead of FindVariableFeatures function from Seurat. I am not sure whether that is the only incompatibility since this is the furthest I've got. Do you plan to update rescue to be compatible with Seurat v3 because I would like to try it out? __

**Comment by seasamgo** [comment]
This is a good point, Seurat v3 was in dev mode at the time that we submitted this but an updated is needed. I'll fix this shortly.

**Comment by seasamgo** [comment]
This is a good point, Seurat v3 was in dev mode at the time that we submitted this but an update is needed. I'll fix this shortly. 

Alternatively, the application of Seurat was originally a compromise to have some method available. Any analysis for genes of interest can be applied and then the gene list indicated using the `select_genes` argument.
