### ISSUE TITLE
bootstrapImputation function. 'breaks' are not unique

### ISSUE THREAD

**Issue by mkorshe** [seasamgo/rescue#11]
Hello!

I have such weird error. How can I deal with it? 
> impute <- rescue::bootstrapImputation(expression_matrix = s_obj@assays$RNA@data) 
Error in cut.default(x = gene_in_cells_detected$mean_expr, breaks = expr_group_breaks,  : 
  'breaks' are not unique

Thank you!

**Comment by seasamgo** [comment]
Hi,

`expr_group_breaks` is defined by `nr_expression_groups` (default 20) when determining variable genes using `computeHVG()`, which is the default when `select_genes` is null. It seems the data may be too small or sparse for these parameters. What are the dimensions of your expression matrix?

My first thought is to define `select_genes` as all the gene names in the matrix.

**Comment by alexandruioanvoda** [comment]
Hi!

I've had the same issue.

So I tried to do as you've indicated, @seasamgo, and define `select_genes` as all the gene names in the matrix.

Instead of solving the problem, it went from the `'breaks' are not unique` error to `Error in f(init, x[[i]]) : non-numeric argument to binary operator`.

**Comment by alexandruioanvoda** [comment]
For reproducibility, I've added the expression matrix (1k cells by 14k genes, log-norm from a public dataset)
[exp.rds.zip](https://github.com/seasamgo/rescue/files/7836259/exp.rds.zip) - attached as a ZIP because github does not support `.rds` files.
Please unzip and then do `exp <- readRDS("/path/to/exp.rds")`.

If you run:
```
require(rescue)
  imp_exp <- bootstrapImputation(
    expression_matrix = exp,            # expression matrix
    select_genes = rownames(exp),
    use_mclapply = TRUE,               # run in parallel
    cores = 10,                          # number of parallel cores
    verbose = TRUE                     # print progress to console
  )
```
You will get:
```
Error in f(init, x[[i]]) : non-numeric argument to binary operator
In addition: Warning messages:
1: In if (class(expression_matrix) != "dgCMatrix") expression_matrix <- methods::as(expression_matrix,  :
  the condition has length > 1 and only the first element will be used
2: In parallel::mclapply(X = 1:bootstrap_samples, mc.preschedule = FALSE,  :
  100 function calls resulted in an error
```

With
```
imp_exp <- bootstrapImputation(
    expression_matrix = exp,            # expression matrix
    use_mclapply = TRUE,               # run in parallel
    cores = 10,                          # number of parallel cores
    verbose = TRUE                     # print progress to console
  )
```
You will get:
```
finding variable genes 
 
using 748 variable genes 
 
Error in f(init, x[[i]]) : non-numeric argument to binary operator
In addition: Warning messages:
1: In if (class(expression_matrix) != "dgCMatrix") expression_matrix <- methods::as(expression_matrix,  :
  the condition has length > 1 and only the first element will be used
2: In parallel::mclapply(X = 1:bootstrap_samples, mc.preschedule = FALSE,  :
  100 function calls resulted in an error
```

**Comment by seasamgo** [comment]
Hi @alexandruioanvoda, and thank you for your interest in rescue! I was able to run both versions of code without the errors you mention. However, I did notice there's an additional warning and checking the class of `exp` indicated it was about an array. Adding `as(exp_sub, "dgCMatrix")` resulted in no warnings or errors for me. 

Could you check this? If it's deeper than that, then we can take a look at our R sessions to compare.
