### ISSUE TITLE
RESCUE issue

### ISSUE THREAD

**Issue by stefanonard85** [seasamgo/rescue#4]
Hello, 

I am trying to run your package. However, all goes fine till I get this error 👍 
Error in system("which python", intern = T) : 'which' not found
any clue?
I think is a problem relative to windows.

<img width="297" alt="Capture" src="https://user-images.githubusercontent.com/16965990/77725780-bd68e080-6fcc-11ea-88c3-d9a5358ddf1a.PNG">

**Comment by RubD** [comment]
Hi Stefanord85,

Yes, you're right. This is an issue due to windows. I've fixed the code and I've made a pull request to @seasamgo . Now it will identify the correct python path on both unix and windows machines, alternatively you will also be able to set your own python path with the new parameter python_path.

`if(is.null(python_path)) {

    if(.Platform[["OS.type"]] == "unix") {
      python_path = try(system("which python", intern = T))
    } else if(.Platform[["OS.type"]] == "windows") {
      python_path = try(system("where python", intern = T))
      if(class(python_path) == "try-error") {
        cat("\n no python path found, set it manually when needed \n")
        python_path = "/set/your/python/path/manually/please/"
      }
    }
  }
  python_path = as.character(python_path)`

Once he has accepted my pull request, it should work for you. Thanks

**Comment by stefanonard85** [comment]
Thanks a lot Ruben. I ll let you know how goes once he accept your pull request.

**Comment by seasamgo** [comment]
Thank you for the patch @RubD , and for bringing this to our attention @stefanonard85

**Comment by stefanonard85** [comment]
Hello @RubD  and @seasamgo  thanks a lot for your help but I am getting this other error and I do not know if it is something that depends from me. I have run  also pip install pandas,
pip install networkx, pip install python-louvain. 
<img width="236" alt="Capture" src="https://user-images.githubusercontent.com/16965990/77813516-a20add80-707f-11ea-9fe4-7ccba574c507.PNG">

**Comment by RubD** [comment]
If you open a python script in your terminal

`python`

Can you then run the code from this [link](https://python-louvain.readthedocs.io/en/latest/)  ?

`import community

import networkx as nx

#better with karate_graph() as defined in networkx example.
#erdos renyi don't have true community structure
G = nx.erdos_renyi_graph(30, 0.05)

#first compute the best partition
partition = community.best_partition(G)

#drawing
size = float(len(set(partition.values())))
pos = nx.spring_layout(G)
count = 0.
for com in set(partition.values()) :
    count = count + 1.
    list_nodes = [nodes for nodes in partition.keys()
                                if partition[nodes] == com]
    nx.draw_networkx_nodes(G, pos, list_nodes, node_size = 20,
                                node_color = str(count / size))


nx.draw_networkx_edges(G, pos, alpha=0.5)`

I just want to know if the python module installation worked or not? Sorry for the trouble.
Ruben

**Comment by stefanonard85** [comment]
It does not recognize import as internal or external command

**Comment by RubD** [comment]
> It does not recognize import as internal or external command

Okay, I did another round of improvements on the installation part of rescue. Unfortunately, I don't have a good way of testing the package on a windows machine, but in theory the user should not have to install any python modules themselves anymore. This should be all automatic now.

Once you have reinstalled rescue it would be good to know if it worked. You could run these commands in R, which should tell you if it can find python and the necessary python modules.

`
reticulate::py_available()   

reticulate::py_config()  
reticulate::py_discover_config()  
reticulate::py_module_available('community')  
reticulate::py_module_available('networkx')  
reticulate::py_module_available('pandas')` 


I've asked @seasamgo to test it first and then he needs to merge my solution before you can install this new version.

**Comment by stefanonard85** [comment]
Hello Ruben, 

I have manually unistalled the package and reinstalled it again . All went fine. Then  I have run your code but keeps giving me the same error, as in the picture I have attached.
<img width="351" alt="Capture" src="https://user-images.githubusercontent.com/16965990/77866105-97775200-71ff-11ea-9c9c-0a4bb69a0eee.PNG">

**Comment by RubD** [comment]
Hi Stefano,

@seasamgo first has to merge my solution before you can download it and use it.
You can however install my version of rescue, which should already work, from:

`devtools::install_github("RubD/rescue")`

That should fix it, since I can see on your snapshot, that it can not find the community module, which will be automatically installed in the new version.

Best,
Ruben

**Comment by stefanonard85** [comment]
Hello Ruben, 

I have manually removed the folder of Rescue and installed it again. However I get always the same error. I have attached 3 snapshots to make you understand the problem better. Part1 , Part2 and part3. Let me know what you think.
<img width="491" alt="1part" src="https://user-images.githubusercontent.com/16965990/77957337-56377e80-72a1-11ea-919c-7ebc6e3700aa.PNG">
<img width="443" alt="2part" src="https://user-images.githubusercontent.com/16965990/77957339-56d01500-72a1-11ea-80e9-41f8c8c7473c.PNG">
<img width="429" alt="3part" src="https://user-images.githubusercontent.com/16965990/77957340-56d01500-72a1-11ea-9cf1-fb6a0d20ab12.PNG">

**Comment by RubD** [comment]
Hi Stefano, 

That's quite a struggle we have here.

I'll try to do this step by step, so that we can figure this out and hopefully this will also help you with other packages that use similar tools.

You can just copy this whole block of code into your script, I assume you use Rstudio.

EDIT: update all packages if asked during installation of rescue

```r
# 1. remove rescue package and restart R session
remove.packages("rescue")  
.rs.restartR()

# 2. install newest version of rescue
devtools::install_github("RubD/rescue")
library(rescue)

# 3. what is the default python path
system('where python', intern = T)

# 4. check reticulate python and if python modules have been installed
# if it asks to install miniconda and python modules, type yes
# the 3 last command should all return TRUE
reticulate::py_config()
reticulate::py_module_available('community')
reticulate::py_module_available('networkx')
reticulate::py_module_available('pandas')

# 5. check which python path is now used by 
system('where python', intern = T)
```

You don't have to install devtools again or do anything else. If we can fix this, then everything should be fixed. Thanks,
Ruben

**Comment by stefanonard85** [comment]
Hello Ruben, 

it works amazingly. Thanks a lot for all your support. I have tried to run on my personal PC a small matrix and all is fine . Now I will run the entire matrix on the cluster. 
Again thx for all your support and compliment for the paper.

**Comment by RubD** [comment]
> Hello Ruben,
> 
> it works amazingly. Thanks a lot for all your support. I have tried to run on my personal PC a small matrix and all is fine . Now I will run the entire matrix on the cluster.
> Again thx for all your support and compliment for the paper.

That's good to hear Stefano. I hope it helps! In theory rescue should now work on any platform and it should install the necessary python modules if required, so the cluster shouldn't be a problem.
Thanks for giving rescue a try!
Ruben
