### ISSUE TITLE
impute Error

### ISSUE THREAD

**Issue by Adominguez-pact** [seasamgo/rescue#7]
Hello, 

Following the tutorial, I get this error when running the impute portion

> impute <- rescue::bootstrapImputation(expression_matrix = expression_dropout@assays$RNA@data)  
Error in `:=`(covariance, (stdev/mean_expr)) : 
  could not find function ":="

any ideas?

**Comment by RubD** [comment]
Hi,

It looks like the data.table package was not loaded. 

Calling `library(data.table)`  first might fix the issue.

**Comment by RubD** [comment]
> Hi,
> 
> It looks like the data.table package was not loaded.
> 
> Calling `library(data.table)` first might fix the issue.

This did not fix the issue, but I have updated the package and now the tutorial should work again. It was a namespace issue.  

FYI, currently it's a good idea to explicitly provide the python path to the function **bootstrapImputation**. This is the path where you have installed the necessary python modules.
